export const gamesSlice = set => ({
  games: [
    {
      id: 1,
      title: 'Abiotic factor',
      categoryId: 1,
      typeId: 2,
      imageUrl: 'https://picsum.photos/500',
      videoUrl: '3amLNBSMP8k',
      rating: 2,
      imagePublicId: 'https://ibb.co/BNc1Dxp/7aaf51b6897461e53951e5e8bd23b221',
      desc: 'cool game',
    },
    {
      id: 2,
      title: 'Sons of the Forest',
      categoryId: 1,
      typeId: 2,
      imageUrl: 'https://picsum.photos/500',
      videoUrl: '8sghWJKPWno',
      rating: 1,
      imagePublicId: 'https://ibb.co/bLxq5yq/f88300b760a817a3a5a98e8ef1c4fdd7',
      desc: 'cool game',
    },
    {
      id: 3,
      title: 'OutLast',
      categoryId: 1,
      typeId: 2,
      imageUrl: 'https://picsum.photos/500',
      videoUrl: 'hCgiwsIUI4g',
      rating: 2,
      imagePublicId: 'https://ibb.co/5BmTrRb/1e6f8be780a6e42050f5ea2bf4bb9562',
      desc: 'cool game',
    },
    {
      id: 4,
      title: 'Abiotic factor',
      categoryId: 1,
      typeId: 2,
      imageUrl: 'https://picsum.photos/500',
      videoUrl: '3amLNBSMP8k',
      rating: 2,
      imagePublicId: 'https://ibb.co/BNc1Dxp/7aaf51b6897461e53951e5e8bd23b221',
      desc: 'cool game',
    },
    {
      id: 5,
      title: 'Sons of the Forest',
      categoryId: 1,
      typeId: 2,
      imageUrl: 'https://picsum.photos/500',
      videoUrl: '8sghWJKPWno',
      rating: 1,
      imagePublicId: 'https://ibb.co/bLxq5yq/f88300b760a817a3a5a98e8ef1c4fdd7',
      desc: 'cool game',
    },
    {
      id: 6,
      title: 'Abiotic factor',
      categoryId: 1,
      typeId: 2,
      imageUrl: 'https://picsum.photos/500',
      videoUrl: '3amLNBSMP8k',
      rating: 2,
      imagePublicId: 'https://ibb.co/BNc1Dxp/7aaf51b6897461e53951e5e8bd23b221',
      desc: 'cool game',
    },
    {
      id: 7,
      title: 'Sons of the Forest',
      categoryId: 1,
      typeId: 2,
      imageUrl: 'https://picsum.photos/500',
      videoUrl: '8sghWJKPWno',
      rating: 1,
      imagePublicId: 'https://ibb.co/bLxq5yq/f88300b760a817a3a5a98e8ef1c4fdd7',
      desc: 'cool game',
    },
    {
      id: 8,
      title: 'OutLast',
      categoryId: 1,
      typeId: 2,
      imageUrl: 'https://picsum.photos/500',
      videoUrl: 'hCgiwsIUI4g',
      rating: 2,
      imagePublicId: 'https://ibb.co/5BmTrRb/1e6f8be780a6e42050f5ea2bf4bb9562',
      desc: 'cool game',
    },
    {
      id: 9,
      title: 'Abiotic factor',
      categoryId: 1,
      typeId: 2,
      imageUrl: 'https://picsum.photos/500',
      videoUrl: '3amLNBSMP8k',
      rating: 2,
      imagePublicId: 'https://ibb.co/BNc1Dxp/7aaf51b6897461e53951e5e8bd23b221',
      desc: 'cool game',
    },
    {
      id: 10,
      title: 'Sons of the Forest',
      categoryId: 1,
      typeId: 2,
      imageUrl: 'https://picsum.photos/500',
      videoUrl: '8sghWJKPWno',
      rating: 1,
      imagePublicId: 'https://ibb.co/bLxq5yq/f88300b760a817a3a5a98e8ef1c4fdd7',
      desc: 'cool game',
    },
  ],
});
